openapi: 3.0.3
info:
  title: Library API
  version: 1.1.0
  description: STD22006
servers:
  - url: https://library.com
tags:
  - name: Books
  - name: Authors
paths:
  /books:
    get:
      tags:
        - Books
      summary: Get all books
      description: The returned books are ordered by updated datetime.
      operationId: getBooks
      parameters:
        - in: query
          name: bookName
          description: Filter return books by given name
          required: false
          schema:
            type: string
        - in: query
          name: intervals
          description: Filter return books by intervals of dates of the releaseDate
          required: false
          schema:
            type: string
            format: date
        #TODO3: add parameter to filter books by intervals of dates of the releaseDate
      responses:
        200:
          description: The list of filtered books
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Book'
      # /books/{id}/authors/{id}            
    put:
      tags:
        - Books
      summary: Create or update a list of books
      operationId: crupdateBooks
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/CrupdateBook'
      responses:
        200:
          description: The list of created or updated books
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Book'
  /books/{bookId}:
    delete:
      tags:
        - Books
      summary: Delete a book
      operationId: deleteBook
      parameters:
        - name: bookId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '400':
          description: Invalid book ID supplied
        '404':
          description: Book not found   

  /authors:
    get:
      tags:
        - Authors
      summary: Get all authors
      description: The returned author are ordered by updated datetime.
      operationId: getAuthors
      parameters:
        - in: query
          name: authorName
          description: Filter returned author by given name. If not provided, then list is not filterd.
          required: false
          schema:
            type: string
      responses:
        200:
          description: The list of filtered authors
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Author'
    put:
      tags:
        - Authors
      summary: Create or update a list of authors
      operationId: crupdateAuthors
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/Author'
      responses:
        200:
          description: The list of created or updated authors
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Author'
   # TODO(Vidéo): Delete many authors               
  /author/{authorId}:
    delete:
      tags:
        - Authors
      summary: Delete an author
      operationId: deleteAuthor
      parameters:
        - name: authorId
          description: Author identifier to be deleted
          in: path
          required: true
          schema:
            type: string
            #type: integer
      responses:
        '200':
          description: The author deleted
        '400':
          description: Invalid author ID supplied
        '404':
          description: Author not found    
  #TODO2: complete GET (can be filtered by name) - PUT - DELETE
components:
  schemas:
    Author:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        sex:
          $ref: '#/components/schemas/Sex'             
      required:
        - id
    Sex:
      type: string
      enum:
        - M
        - F
    Book:
      type: object
      discriminator:
        propertyName: bookType
      properties:
        id:
          type: string
        bookName:
          type: string
        author:
          $ref: '#/components/schemas/Author'
          #TODO1: set it as a component with properties : id, name, sex (M or F)
          #type: string
        pageNumbers:
          type: integer
        topic:
          type: string
          enum:
            - ROMANCE
            - COMEDY
            - OTHER
        releaseDate:
          type: string
          format: date

    # ... used as the discriminator value
    CrupdateBook:
      description: A representation
      allOf:
        - $ref: '#/components/schemas/Book'
        - type: object

          # properties: add others properties + required
          properties:
            testOne:
              type: string
          required:
            - "testOne"
